version: "3"
services:
  db:
    image: postgres:12.1-alpine
    container_name: postgres_12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ~/Desktop/postdata:/var/lib/postgresql/data